services:
  uplift-me-rest-api:
    container_name: uplift-me-rest-api
    image: ihsanashi/uplift-me-rest-api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - uplift-me-db

  uplift-me-db:
    container_name: uplift-me-db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=uplift-me-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - uplift-me-rest-api:/var/lib/postgresql/data

volumes:
  uplift-me-rest-api: {}